import { Mission } from '../types';

export const INITIAL_KERALA_MISSIONS: Mission[] = [
  {
    id: 'chaya_delivery',
    title: 'Tea & Discussions (ചായയും ചർച്ചയും)',
    malayalamTitle: 'ചായയും ചർച്ചയും 🍵',
    category: 'Delivery',
    desc: 'Pick up 3 hot Sulaimani teas from Nair’s Chaya Kada and deliver them to Abu Backer Kakka at the Mosque and the Auto Stand before they get cold!',
    malayalamDesc: 'നായരുടെ ചായക്കടയിൽ നിന്ന് 3 ചൂടുള്ള സുലൈമാനി വാങ്ങി പള്ളിയിലെ അബൂബക്കർ കാക്കയ്ക്കും ഓട്ടോ സ്റ്റാൻഡിലും എത്തിക്കുക!',
    reward: 150,
    icon: '🍵',
    timeLimit: 120,
    timeRemaining: 120,
    currentStepIndex: 0,
    isCompleted: false,
    isActive: false,
    steps: [
      {
        id: 'step_chaya_pickup',
        desc: 'Go to Nair’s Chaya Kada (-65, 0, -18) to collect the tea flask',
        malayalamDesc: 'ചായ ഫ്ലാസ്ക് വാങ്ങാൻ നായരുടെ ചായക്കടയിലേക്ക് പോവുക (-65, -18)',
        targetCoords: { x: -65, z: -18 },
        isDone: false,
      },
      {
        id: 'step_chaya_mosque',
        desc: 'Deliver first cup to Abu Backer Kakka at Juma Mosque (-72, 0, -42)',
        malayalamDesc: 'ആദ്യ കപ്പ് പള്ളിയിലെ അബൂബക്കർ കാക്കയ്ക്ക് നൽകുക (-72, -42)',
        targetCoords: { x: -72, z: -42 },
        isDone: false,
      },
      {
        id: 'step_chaya_town',
        desc: 'Deliver remaining tea to the Babu Auto Stand in Town Center (0, 0, 0)',
        malayalamDesc: 'ബാക്കി ചായ ടൗൺ സെന്ററിലെ ഓട്ടോ സ്റ്റാൻഡിൽ എത്തിക്കുക (0, 0)',
        targetCoords: { x: 0, z: 0 },
        isDone: false,
      },
    ],
  },
  {
    id: 'goat_chase',
    title: 'The Great Goat Chase (ആട് തോമയെ പിടിക്കൂ!)',
    malayalamTitle: 'ആട് തോമയെ പിടിക്കൂ! 🐐',
    category: 'Story',
    desc: 'Aadu Thoma has escaped from the Old Village yard and is creating mischief around the Lotus Cove! Track him down and calm him with tender grass.',
    malayalamDesc: 'ആട് തോമ കയറുപൊട്ടിച്ച് ആമ്പൽക്കുളത്തിലേക്ക് ഓടിപ്പോയി! അവനെ പിന്തുടർന്ന് പിടിക്കുക.',
    reward: 200,
    icon: '🐐',
    timeLimit: 90,
    timeRemaining: 90,
    currentStepIndex: 0,
    isCompleted: false,
    isActive: false,
    steps: [
      {
        id: 'step_goat_spot',
        desc: 'Locate Aadu Thoma near the Lotus Pond (-80, 0, -75)',
        malayalamDesc: 'താമരക്കുളത്തിനടുത്ത് ആട് തോമയെ കണ്ടെത്തുക (-80, -75)',
        targetCoords: { x: -80, z: -75 },
        isDone: false,
      },
      {
        id: 'step_goat_corral',
        desc: 'Guide Aadu Thoma safely back to the village pasture (-60, 0, -20)',
        malayalamDesc: 'തോമയെ തിരികെ പഴയ ഗ്രാമത്തിലേക്ക് കൂട്ടിക്കൊണ്ടു വരിക (-60, -20)',
        targetCoords: { x: -60, z: -20 },
        isDone: false,
      },
    ],
  },
  {
    id: 'farmer_tractor_help',
    title: 'Paddy Field Ploughing (പാടത്തെ ട്രാക്ടർ പണി)',
    malayalamTitle: 'പാടത്തെ ട്രാക്ടർ പണി 🚜',
    category: 'Farming',
    desc: 'Farmer Raghavan needs help preparing the flooded paddy fields for monsoon planting. Drive the Kerala farm tractor across all 3 field bunds.',
    malayalamDesc: 'രാഘവേട്ടന്റെ വയലിൽ ട്രാക്ടർ ഓടിച്ച് മണ്ണൊരുക്കാൻ സഹായിക്കുക.',
    reward: 350,
    icon: '🚜',
    currentStepIndex: 0,
    isCompleted: false,
    isActive: false,
    steps: [
      {
        id: 'step_tractor_board',
        desc: 'Mount the Red Farm Tractor parked at Paddy Village (-130, 0, 90)',
        malayalamDesc: 'നെൽപ്പാടത്ത് പാർക്ക് ചെയ്തിരിക്കുന്ന ചുവപ്പ് ട്രാക്ടറിൽ കയറുക (-130, 90)',
        targetCoords: { x: -130, z: 90 },
        isDone: false,
      },
      {
        id: 'step_tractor_field_1',
        desc: 'Plough field sector North (-120, 0, 75)',
        malayalamDesc: 'വടക്കേ വയലിൽ ഉഴുക (-120, 75)',
        targetCoords: { x: -120, z: 75 },
        isDone: false,
      },
      {
        id: 'step_tractor_field_2',
        desc: 'Plough field sector South (-145, 0, 105)',
        malayalamDesc: 'തെക്കേ വയലിൽ ഉഴുക (-145, 105)',
        targetCoords: { x: -145, z: 105 },
        isDone: false,
      },
    ],
  },
  {
    id: 'ksrtc_express_trip',
    title: 'High-Range Coach Run (ഹൈവേ ബസ് ട്രിപ്പ്)',
    malayalamTitle: 'ഹൈവേ കോച്ച് ട്രിപ്പ് 🚌',
    category: 'Driving',
    desc: 'Drive the Modern Luxury Coach Bus from the Kizhakkumpuram Bus Terminal down through the Big Highway to the South Coast Beach.',
    malayalamDesc: 'ലക്ഷ്വറി കോച്ച് ബസ് ഓടിച്ച് ടൗൺ സ്റ്റാൻഡിൽ നിന്ന് കടൽത്തീരത്തേക്ക് എത്തിക്കുക.',
    reward: 400,
    icon: '🚌',
    currentStepIndex: 0,
    isCompleted: false,
    isActive: false,
    steps: [
      {
        id: 'step_bus_start',
        desc: 'Take the Luxury Coach Bus at the Bus Stand Bay (24, 0, 14)',
        malayalamDesc: 'ബസ് സ്റ്റാൻഡിൽ നിന്ന് ലക്ഷ്വറി കോച്ച് എടുക്കുക (24, 14)',
        targetCoords: { x: 24, z: 14 },
        isDone: false,
      },
      {
        id: 'step_bus_bridge',
        desc: 'Cross the Big River Highway Bridge (0, 0, 145)',
        malayalamDesc: 'വലിയ പുഴ ഹൈവേ പാലം മുറിച്ചുകടക്കുക (0, 145)',
        targetCoords: { x: 0, z: 145 },
        isDone: false,
      },
      {
        id: 'step_bus_beach',
        desc: 'Park at the South Coast Lighthouse Beach Bus Bay (0, 0, 310)',
        malayalamDesc: 'ലൈറ്റ്ഹൗസ് ബീച്ചിലെ ബസ് ബേയിൽ നിർത്തുക (0, 310)',
        targetCoords: { x: 0, z: 310 },
        isDone: false,
      },
    ],
  },
  {
    id: 'sevens_football_match',
    title: 'Sevens Stadium Match (സെവൻസ് ഫുട്ബോൾ!)',
    malayalamTitle: 'സെവൻസ് ഫുട്ബോൾ ചലഞ്ച് ⚽',
    category: 'Sports',
    desc: 'Enter the floodlit Kizhakkumpuram Sevens football ground and score 3 winning goals to make the village proud!',
    malayalamDesc: 'ഫ്ലഡ്‌ലൈറ്റ് സ്റ്റേഡിയത്തിൽ കയറി 3 ഗോളുകൾ അടിച്ച് നാട്ടിലെ ഹീറോ ആവുക!',
    reward: 250,
    icon: '⚽',
    currentStepIndex: 0,
    isCompleted: false,
    isActive: false,
    steps: [
      {
        id: 'step_stadium_enter',
        desc: 'Enter the Sevens Football Ground (110, 0, -80)',
        malayalamDesc: 'സെവൻസ് ഫുട്ബോൾ ഗ്രൗണ്ടിൽ പ്രവേശിക്കുക (110, -80)',
        targetCoords: { x: 110, z: -80 },
        isDone: false,
      },
      {
        id: 'step_score_goals',
        desc: 'Shoot the ball into the net 3 times!',
        malayalamDesc: 'പന്ത് 3 തവണ വലയിലാക്കുക!',
        targetCoords: { x: 110, z: -80 },
        isDone: false,
      },
    ],
  },
  {
    id: 'coastal_fish_delivery',
    title: 'Harbour Fish Cargo (ഹാർബർ മീൻ ചന്ത)',
    malayalamTitle: 'ഹാർബർ മീൻ വരവ് 🐟',
    category: 'Delivery',
    desc: 'Collect fresh mackerel and kingfish crates directly from the fishermen catamaran boats at South Beach and deliver to Daily Fish Market.',
    malayalamDesc: 'കടൽത്തീരത്ത് നിന്ന് പുതിയ മീൻ പെട്ടികൾ വാങ്ങി കിഴക്കുംപുറം ചന്തയിലെത്തിക്കുക.',
    reward: 300,
    icon: '🐟',
    timeLimit: 150,
    timeRemaining: 150,
    currentStepIndex: 0,
    isCompleted: false,
    isActive: false,
    steps: [
      {
        id: 'step_fish_pickup',
        desc: 'Pick up fresh fish crates from Lighthouse Beach (0, 0, 320)',
        malayalamDesc: 'ബീച്ചിലെ കാറ്റമരൻ വള്ളങ്ങളിൽ നിന്ന് മീൻ പെട്ടികൾ എടുക്കുക (0, 320)',
        targetCoords: { x: 0, z: 320 },
        isDone: false,
      },
      {
        id: 'step_fish_market',
        desc: 'Deliver fresh catch to Daily Bazaar Stalls (85, 0, 10)',
        malayalamDesc: 'ചന്തയിലെ മീൻ സ്റ്റാളിൽ എത്തിക്കുക (85, 10)',
        targetCoords: { x: 85, z: 10 },
        isDone: false,
      },
    ],
  },
];
