import { RandomSceneEvent } from '../types';

export const RANDOM_NAATTILE_SCENES: RandomSceneEvent[] = [
  {
    id: 'scene_cow_block',
    title: 'Gomatha Highway Blockade (പശു റോഡിൽ!)',
    malayalamTitle: 'പശു റോഡിൽ ധ്യാനത്തിൽ! 🐄',
    desc: 'A hefty village cow named Lakshmi has decided that the middle of the main tarmac road is the prime spot for an afternoon nap.',
    malayalamDesc: 'ലക്ഷ്മി പശു റോഡിന്റെ നടുവിൽ സുഖമായി കിടന്ന് അയവെട്ടുകയാണ്! വണ്ടികൾ ഇരുവശത്തും കിടക്കുന്നു.',
    avatar: '🐄',
    location: 'Main Road Junction',
    choices: [
      {
        text: 'Offer tender banana leaf from roadside stall',
        malayalamText: 'ഒരു വാഴയില കാണിച്ച് സൈഡിലേക്ക് മാറ്റുക',
        reward: 50,
        reaction: 'Lakshmi happily follows the banana leaf off the road. The whole traffic claps: “നല്ല മനസ്സിന് നന്ദി മോനേ!”',
        malayalamReaction: 'പശു വാഴയില കണ്ട് പതുക്കെ സൈഡിലേക്ക് മാറി. നാട്ടുകാർ കയ്യടിച്ചു!',
        sound: 'coin',
      },
      {
        text: 'Blast the loud Kerala musical air horn [H]',
        malayalamText: 'എയർ ഹോൺ നീട്ടി അടിക്കുക',
        reaction: 'Lakshmi looks at you with supreme indifference and lets out a thunderous “അമ്മാഹ്ഹ്ഹ്!” without moving an inch.',
        malayalamReaction: 'പശു മൈൻഡ് പോലും ചെയ്തില്ല! ഒരു വലിയ “അമ്മാഹ്ഹ്ഹ്!” വിളി മാത്രം.',
        sound: 'moo',
      },
      {
        text: 'Wait patiently like a true Malayali',
        malayalamText: 'ക്ഷമയോടെ കാത്തിരിക്കുക',
        reward: 20,
        reaction: 'After 30 seconds of intense philosophical contemplation, the cow gets up and wanders to the grass.',
        malayalamReaction: 'പശു പതുക്കെ എഴുന്നേറ്റ് പുല്ലു തിന്നാൻ പോയി. വഴി ക്ലിയർ!',
        sound: 'bell',
      },
    ],
  },
  {
    id: 'scene_parking_argument',
    title: 'The Great Parking Debate (പാർക്കിംഗ് തർക്കം!)',
    malayalamTitle: 'ഓട്ടോ ചേട്ടനും മാരുതി ചേട്ടനും തർക്കം! 🗣️',
    desc: 'Two uncles in starched mundus are vigorously debating the geometry of a parking slot outside the bakery with full hand gestures.',
    malayalamDesc: '“ഇവിടെ വണ്ടി നിർത്തിയാൽ എന്റെ ഓട്ടോ എങ്ങനെ തിരിക്കും ചേട്ടാ?” — ചായക്കട മുഴുവൻ കാഴ്ചക്കാരായി കൂടി!',
    avatar: '🗣️',
    location: 'Bakery Junction',
    choices: [
      {
        text: 'Order 2 Sulaimani teas from Nair Kada to calm them down',
        malayalamText: 'രണ്ടുപേർക്കും ഓരോ സുലൈമാനി വാങ്ങി കൊടുക്കുക',
        reward: 60,
        reaction: 'Both uncles instantly stop arguing, sip their tea together and start talking about football. Peace restored!',
        malayalamReaction: 'സുലൈമാനി കണ്ടതും രണ്ടുപേരും തർക്കം നിർത്തി ഫുട്ബോൾ വിശേഷം തുടങ്ങി!',
        sound: 'coin',
      },
      {
        text: 'Jump into Babu’s Auto and demonstrate tight parking',
        malayalamText: 'ഓട്ടോ സൂപ്പർ ആയി റിവേഴ്സ് എടുത്ത് കാണിച്ചു കൊടുക്കുക',
        reward: 80,
        reaction: 'You slide the auto into the tight gap with 1 inch margin. The crowd roars: “ഇതാണ് ഡ്രൈവിംഗ്!”',
        malayalamReaction: 'സൂപ്പർ ഡ്രൈവിംഗ്! കാണികൾ ആർത്തുവിളിച്ചു!',
        sound: 'airhorn',
      },
      {
        text: 'Referee the debate like a Sevens match',
        malayalamText: 'റഫറിയെപ്പോലെ വിസിൽ അടിക്കുക',
        reaction: 'You blow the whistle. Both uncles look confused, laugh loudly and shake hands.',
        malayalamReaction: 'വിസിൽ കേട്ട് രണ്ടുപേരും ചിരിച്ച് കൈകൊടുത്തു പിരിഞ്ഞു.',
        sound: 'whistle',
      },
    ],
  },
  {
    id: 'scene_wedding_procession',
    title: 'Surprise Wedding Melam (കല്യാണ ഘോഷയാത്ര!)',
    malayalamTitle: 'കല്യാണ ഘോഷയാത്രയും ചെണ്ടമേളവും! 🥁',
    desc: 'A festive local wedding procession accompanied by an energetic 8-member Chenda Melam troupe is marching down the village road!',
    malayalamDesc: 'തക തക തിമി! ചെണ്ടമേളത്തിന്റെ അകമ്പടിയോടെ കല്യാണ സംഘം റോഡിലേക്ക് ഇറങ്ങി!',
    avatar: '🥁',
    location: 'Temple Road',
    choices: [
      {
        text: 'Join the rhythm and dance in celebration',
        malayalamText: 'ചെണ്ടമേളത്തിനൊപ്പം തുള്ളിച്ചാടുക',
        reward: 100,
        reaction: 'The wedding party gives you a box of fresh Kozhikodan Halwa and congratulations! You feel energized!',
        malayalamReaction: 'കല്യാണവീട്ടുകാർ സന്തോഷത്തോടെ നിങ്ങൾക്ക് നല്ല അസ്സൽ കോഴിക്കോടൻ ഹൽവ തന്നു!',
        sound: 'chenda',
      },
      {
        text: 'Synchronize the bus air horn with the Chenda beats',
        malayalamText: 'എയർ ഹോൺ മേളത്തിനൊപ്പം താളത്തിൽ അടിക്കുക',
        reward: 70,
        reaction: 'The Chenda artists love the fusion and speed up the tempo! Maximum excitement in the village!',
        malayalamReaction: 'എയർ ഹോണും ചെണ്ടമേളവും ഒത്തുചേർന്ന് റോഡ് ഇളക്കിമറിച്ചു!',
        sound: 'airhorn',
      },
    ],
  },
  {
    id: 'scene_football_chase',
    title: 'Runaway Football! (കുട്ടികളുടെ ഫുട്ബോൾ!)',
    malayalamTitle: 'കുട്ടികളുടെ ഫുട്ബോൾ റോഡിലേക്ക്! ⚽',
    desc: 'A thunderous volley from the local school ground sent the ball bouncing straight across the tarmac highway with 4 kids running after it!',
    malayalamDesc: 'സ്കൂൾ ഗ്രൗണ്ടിൽ നിന്ന് ഒരു നീളൻ ഷോട്ട് റോഡിലേക്ക് തെറിച്ചുവീണു!',
    avatar: '⚽',
    location: 'School Ground Bend',
    choices: [
      {
        text: 'Bicycle kick the ball cleanly back into the stadium',
        malayalamText: 'ഫസ്റ്റ് ടച്ചിൽ തന്നെ പന്ത് ഗ്രൗണ്ടിലേക്ക് തിരിച്ചടിക്കുക',
        reward: 90,
        reaction: 'A curving screamer straight into the goalposts! The kids cheer: “റൊണാൾഡോ ആണോ ബ്രോ?!”',
        malayalamReaction: 'ഗ്രൗണ്ടിലേക്ക് ഉഗ്രൻ കിക്ക്! കുട്ടികൾ കയ്യടിച്ച് ആർത്തുവിളിച്ചു!',
        sound: 'goal',
      },
      {
        text: 'Gently stop your vehicle and signal the kids safely across',
        malayalamText: 'വണ്ടി നിർത്തി കുട്ടികളെ സുരക്ഷിതമായി റോഡ് ക്രോസ്സ് ചെയ്യിക്കുക',
        reward: 40,
        reaction: 'The kids wave cheerfully: “താങ്ക്യൂ ചേട്ടാ!” and run back to resume the Sevens tournament.',
        malayalamReaction: 'കുട്ടികൾ സന്തോഷത്തോടെ കൈവീശി പന്തുമായി കളി തുടർന്നു.',
        sound: 'whistle',
      },
    ],
  },
  {
    id: 'scene_auto_dialogue',
    title: 'Auto Chettan’s Meter Dialogue (ഓട്ടോ ചേട്ടന്റെ ഡയലോഗ്!)',
    malayalamTitle: '“മീറ്റർ ഇടാൻ പറ്റില്ല മോനേ!” 🛺',
    desc: 'A passenger asking for a ride to the hill viewpoint gets the legendary Kerala auto driver response.',
    malayalamDesc: '“മലമുകളിലേക്ക് പോയാൽ റിട്ടേൺ ആളെ കിട്ടില്ല മോനേ! ഒന്നര മീറ്റർ തന്നാൽ ആലോചിക്കാം!”',
    avatar: '🛺',
    location: 'Town Auto Stand',
    choices: [
      {
        text: 'Agree with a warm smile and offer a cup of tea',
        malayalamText: '“ശരി ചേട്ടാ, പോകുന്ന വഴിക്ക് ഒരു ചായയും കുടിക്കാം!”',
        reward: 50,
        reaction: 'Auto Chettan grins: “ആഹ് അങ്ങനെയെങ്കിൽ കേറിക്കോ! വളവുകളിൽ നല്ല ശ്രദ്ധയോടെ ഓടിക്കാം!”',
        malayalamReaction: 'ചേട്ടൻ ചിരിച്ച് വണ്ടി സ്റ്റാർട്ടാക്കി: “എന്നാൽ കേറിക്കോളൂ!”',
        sound: 'autohorn',
      },
      {
        text: 'Tell him you are driving the Luxury Bus yourself today',
        malayalamText: '“ഞാൻ ഇന്ന് ലക്ഷ്വറി ബസ് ആണ് ഓടിക്കുന്നത്!”',
        reward: 30,
        reaction: 'Auto Chettan nods with deep respect: “ഹോ! അപ്പൊ നമ്മൾ കൊളീഗ്സ് ആണ്! പോയി കലിപ്പിൽ വണ്ടി ഓടിക്ക്!”',
        malayalamReaction: 'ചേട്ടൻ സല്യൂട്ട് ചെയ്തു: “സൂപ്പർ ഡ്രൈവർ!”',
        sound: 'airhorn',
      },
    ],
  },
];
