export interface MenuItem {
  id: string;
  name: string;
  malayalamName: string;
  price: number;
  category: 'chaya' | 'breakfast' | 'meals' | 'snacks' | 'drinks' | 'combos' | 'unlocked';
  icon: string;
  description: string;
  malayalamDescription: string;
  isSpicy?: boolean;
  isHot?: boolean;
  isVeg?: boolean;
  requiredReputationLevel?: number;
}

export interface ThattukadaReputationLevel {
  level: number;
  title: string;
  malayalamTitle: string;
  ordersRequired: number;
  perkDescription: string;
  unlockedItemNames: string[];
  badgeColor: string;
}

export const REPUTATION_LEVELS: ThattukadaReputationLevel[] = [
  {
    level: 1,
    title: 'New Customer',
    malayalamTitle: 'പുതിയ ആൾ',
    ordersRequired: 0,
    perkDescription: 'Fresh face at Mohanan Nair’s tea stall. Regular pricing applies.',
    unlockedItemNames: [],
    badgeColor: '#a1a1aa',
  },
  {
    level: 2,
    title: 'Regular Customer',
    malayalamTitle: 'സ്ഥിരം കസ്റ്റമർ',
    ordersRequired: 3,
    perkDescription: 'Nair Chettan greets you with a warm smile! Unlocks Special Spiced Sulaimani & 5% off teas.',
    unlockedItemNames: ['നായരുടെ സ്പെഷ്യൽ സുലൈമാനി'],
    badgeColor: '#38bdf8',
  },
  {
    level: 3,
    title: 'Village Promani',
    malayalamTitle: 'നാട്ടിലെ പ്രമാണി',
    ordersRequired: 7,
    perkDescription: 'Reserved front bench seat! Unlocks Double Roasted Beef Fry & free crisp pappadam.',
    unlockedItemNames: ['ഡബിൾ ബീഫ് ഫ്രൈ സ്പെഷ്യൽ'],
    badgeColor: '#fbbf24',
  },
  {
    level: 4,
    title: 'Thattukada VIP Legend',
    malayalamTitle: 'തട്ടുകട VIP',
    ordersRequired: 12,
    perkDescription: 'VIP status in Kizhakkumpuram! Unlocks Royal Kizhi Porotta Feast and instant piping tea refills.',
    unlockedItemNames: ['രാജകീയ കിഴി പൊറോട്ട ഫീസ്റ്റ്'],
    badgeColor: '#ec4899',
  },
];

export const THATTUKADA_MENU: MenuItem[] = [
  // ☕ ചായ & ചൂടുപാനീയങ്ങൾ
  {
    id: 'chaya',
    name: 'Kerala Milk Tea',
    malayalamName: 'ചായ',
    price: 10,
    category: 'chaya',
    icon: '☕',
    description: 'Piped hot foamy Kerala tea meter-poured in a glass tumbler',
    malayalamDescription: 'നല്ല പതപ്പിച്ച നാടൻ പാൽ ചായ',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'kattan_chaya',
    name: 'Kattan Chaya (Black Tea)',
    malayalamName: 'കട്ടൻ ചായ',
    price: 10,
    category: 'chaya',
    icon: '🫖',
    description: 'Strong, aromatic black tea with fresh crushed tea leaves',
    malayalamDescription: 'കടുപ്പമുള്ള നാടൻ കട്ടൻ ചായ',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'paluchaya',
    name: 'Paluchaya (Rich Milk Tea)',
    malayalamName: 'പാലുചായ',
    price: 15,
    category: 'chaya',
    icon: '🥛',
    description: 'Extra thick creamy cows milk tea whipped high with rich froth',
    malayalamDescription: 'നല്ല കൊഴുത്ത പാൽ ചേർത്ത ചൂട് ചായ',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'kattan_kaapi',
    name: 'Kattan Kaapi (Black Coffee)',
    malayalamName: 'കട്ടൻ കാപ്പി',
    price: 15,
    category: 'chaya',
    icon: '☕',
    description: 'Traditional roasted Wayanad black coffee with dried ginger & jaggery',
    malayalamDescription: 'വയനാടൻ പൊടി കൊണ്ടുള്ള കടുപ്പമുള്ള കട്ടൻ കാപ്പി',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'coffee',
    name: 'Coffee (Milk Coffee)',
    malayalamName: 'കോഫി',
    price: 20,
    category: 'chaya',
    icon: '☕',
    description: 'Strong South Indian style filter coffee with frothy hot milk',
    malayalamDescription: 'നല്ല മണമുള്ള ചൂട് ഫിൽട്ടർ കോഫി',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'sulaimani',
    name: 'Sulaimani (Spiced Lemon Tea)',
    malayalamName: 'സുലൈമാനി',
    price: 15,
    category: 'chaya',
    icon: '🍋',
    description: 'Golden spiced tea brewed with cardamom, clove, mint, and freshly squeezed lemon',
    malayalamDescription: 'ഏലക്കയും നാരങ്ങാനീരും ചേർത്ത സ്പെഷ്യൽ സുലൈമാനി',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'inji_chaya',
    name: 'Inji Chaya (Ginger Tea)',
    malayalamName: 'ഇഞ്ചി ചായ',
    price: 15,
    category: 'chaya',
    icon: '🫚',
    description: 'Crushed fresh ginger and spices infused with steaming tea',
    malayalamDescription: 'പച്ച ഇഞ്ചി ചതച്ചിട്ട് തിളപ്പിച്ച ചൂട് ചായ',
    isHot: true,
    isVeg: true,
  },

  // 🍳 രാവിലത്തെ സ്പെഷ്യൽ
  {
    id: 'puttu_kadala',
    name: 'Puttu + Kadala Curry',
    malayalamName: 'പുട്ട് + കടല',
    price: 40,
    category: 'breakfast',
    icon: '🥥',
    description: 'Steamed rice puttu layered with fresh grated coconut & spicy black chickpea gravy',
    malayalamDescription: 'നല്ല ആവി പറക്കുന്ന അരിപ്പുട്ടും നാടൻ കടലക്കറിയും',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'appam_mutta',
    name: 'Appam + Mutta Curry',
    malayalamName: 'അപ്പം + മുട്ടക്കറി',
    price: 50,
    category: 'breakfast',
    icon: '🍳',
    description: 'Soft laced palappam served with spicy double egg roasted gravy',
    malayalamDescription: 'പാലപ്പവും തേങ്ങാപ്പാൽ ചേർത്ത മുട്ടക്കറിയും',
    isHot: true,
  },
  {
    id: 'dosa_chutney',
    name: 'Dosa + Chutney',
    malayalamName: 'ദോശ + ചട്ണി',
    price: 30,
    category: 'breakfast',
    icon: '🥞',
    description: 'Three crispy thattudosa served with fiery red chili & fresh coconut chutneys',
    malayalamDescription: 'ചൂട് തട്ടുദോശയും തേങ്ങാച്ചട്ണിയും മുളക് ചട്ണിയും',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'porotta_curry',
    name: 'Porotta + Curry',
    malayalamName: 'പൊറോട്ട + കറി',
    price: 50,
    category: 'breakfast',
    icon: '🫓',
    description: 'Flaky layered Kerala maida porottas paired with rich vegetable or egg gravy',
    malayalamDescription: 'നല്ല പഞ്ഞിപോലെയുള്ള ലെയർ പൊറോട്ടയും സ്പെഷ്യൽ കറിയും',
    isHot: true,
  },
  {
    id: 'bread_omelette',
    name: 'Bread + Omelette',
    malayalamName: 'ബ്രെഡ് + ഓംലറ്റ്',
    price: 35,
    category: 'breakfast',
    icon: '🥪',
    description: 'Fresh local bakery bread toasted with spiced onion-green chili omelette',
    malayalamDescription: 'സവാളയും പച്ചമുളകും ചേർത്ത ഓംലറ്റും ടോസ്റ്റ് ബ്രെഡും',
    isHot: true,
  },
  {
    id: 'mutta_bullseye',
    name: 'Mutta Bullseye',
    malayalamName: 'മുട്ട ബുൾസൈ',
    price: 20,
    category: 'breakfast',
    icon: '🍳',
    description: 'Sunny side up fried egg seasoned with crushed black pepper and rock salt',
    malayalamDescription: 'കുരുമുളകുപൊടി തൂവിയ ചൂട് മുട്ട ബുൾസൈ',
    isHot: true,
  },
  {
    id: 'mutta_omelette',
    name: 'Mutta Omelette',
    malayalamName: 'മുട്ട ഓംലറ്റ്',
    price: 25,
    category: 'breakfast',
    icon: '🍳',
    description: 'Fluffy country egg omelette with shallots, curry leaves, and green chillies',
    malayalamDescription: 'ചെറിയ ഉള്ളിയും വേപ്പിലയും ചേർത്ത നല്ല നാടൻ മുട്ട ഓംലറ്റ്',
    isHot: true,
  },

  // 🍗 തട്ടുകട സ്പെഷ്യൽ
  {
    id: 'porotta_beef',
    name: 'Porotta + Beef Curry',
    malayalamName: 'പൊറോട്ട + ബീഫ് കറി',
    price: 90,
    category: 'meals',
    icon: '🥩',
    description: 'The iconic Kerala combo: hot beaten porottas drenched in spicy roasted beef gravy',
    malayalamDescription: 'കേരളത്തിന്റെ ദേശീയ വിഭവം: ചൂട് പൊറോട്ടയും നാടൻ ബീഫ് കറിയും',
    isHot: true,
    isSpicy: true,
  },
  {
    id: 'chicken_fry',
    name: 'Thattukada Chicken Fry',
    malayalamName: 'ചിക്കൻ ഫ്രൈ',
    price: 100,
    category: 'meals',
    icon: '🍗',
    description: 'Crispy deep-fried bone-in chicken marinated in shallots, ginger-garlic & curry leaves',
    malayalamDescription: 'തട്ടുകട സ്പെഷ്യൽ എണ്ണയിലിട്ട് വറുത്ത കോഴിക്കഷണം',
    isHot: true,
    isSpicy: true,
  },
  {
    id: 'beef_fry',
    name: 'Kerala Beef Fry (Ularthiyathu)',
    malayalamName: 'ബീഫ് ഫ്രൈ',
    price: 110,
    category: 'meals',
    icon: '🥘',
    description: 'Slow-roasted beef cubes tossed with coconut slices (തേങ്ങാക്കൊത്ത്) and pepper',
    malayalamDescription: 'തേങ്ങാക്കൊത്തും കുരുമുളകും ചേർത്ത് വരട്ടിയെടുത്ത ബീഫ് ഫ്രൈ',
    isHot: true,
    isSpicy: true,
  },
  {
    id: 'chicken_chilli',
    name: 'Thattukada Chicken Chilli',
    malayalamName: 'ചിക്കൻ ചില്ലി',
    price: 100,
    category: 'meals',
    icon: '🌶️',
    description: 'Spicy Kerala street-style chilli chicken with green chillies & capsicum',
    malayalamDescription: 'പച്ചമുളകും ഉള്ളിയും ചേർത്ത നാടൻ ചിക്കൻ ചില്ലി',
    isHot: true,
    isSpicy: true,
  },
  {
    id: 'mutta_curry',
    name: 'Nadan Mutta Curry',
    malayalamName: 'മുട്ട കറി',
    price: 40,
    category: 'meals',
    icon: '🍲',
    description: 'Hard boiled eggs in thick coconut & onion masala gravy',
    malayalamDescription: 'മസാല ചേർത്ത കൊഴുത്ത നാടൻ മുട്ടക്കറി',
    isHot: true,
  },
  {
    id: 'kappa_meen',
    name: 'Kappa + Meen Curry',
    malayalamName: 'കപ്പ + മീൻ കറി',
    price: 80,
    category: 'meals',
    icon: '🐟',
    description: 'Steamed mashed tapioca tempered with mustard & fiery red fish curry with kodampuli',
    malayalamDescription: 'കുടംപുളിയിട്ട് വച്ച എരിവുള്ള മീൻ കറിയും വേവിച്ച കപ്പയും',
    isHot: true,
    isSpicy: true,
  },
  {
    id: 'kappa_beef',
    name: 'Kappa + Beef (Kappa Biryani)',
    malayalamName: 'കപ്പ + ബീഫ്',
    price: 90,
    category: 'meals',
    icon: '🍲',
    description: 'Tender tapioca chunks cooked together with roasted spiced beef and bone marrow',
    malayalamDescription: 'കപ്പയും ബീഫും ചേർത്തുണ്ടാക്കിയ കൊതിയൂറുന്ന എരിവുള്ള കൂട്ട്',
    isHot: true,
    isSpicy: true,
  },

  // 🍟 സ്നാക്സ്
  {
    id: 'pazham_pori',
    name: 'Pazham Pori (Banana Fritters)',
    malayalamName: 'പഴംപൊരി',
    price: 15,
    category: 'snacks',
    icon: '🍌',
    description: 'Golden, crispy sweet ripe Nendran banana slices fried in batter',
    malayalamDescription: 'നല്ല മധുരമുള്ള നേന്ത്രപ്പഴം വറുത്ത ചൂട് പഴംപൊരി',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'uzhunnu_vada',
    name: 'Uzhunnu Vada (Medu Vada)',
    malayalamName: 'ഉഴുന്നുവട',
    price: 15,
    category: 'snacks',
    icon: '🥯',
    description: 'Crispy golden urad dal donut fritter with ginger and peppercorns',
    malayalamDescription: 'മൊരിഞ്ഞ നാടൻ ഉഴുന്നുവട',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'parippu_vada',
    name: 'Parippu Vada (Dal Fritter)',
    malayalamName: 'പരിപ്പ് വട',
    price: 15,
    category: 'snacks',
    icon: '🍘',
    description: 'Crunchy Bengal gram fritters packed with shallots, dried red chillies and curry leaves',
    malayalamDescription: 'ചായക്കടയിലെ ചൂടൻ മൊരിഞ്ഞ പരിപ്പുവട',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'ulli_vada',
    name: 'Ulli Vada (Onion Fritter)',
    malayalamName: 'ഉള്ളിവട',
    price: 15,
    category: 'snacks',
    icon: '🧅',
    description: 'Thinly sliced shallots coated in spiced flour and fried super crisp',
    malayalamDescription: 'സവാളയും പച്ചമുളകും ചേർത്ത നല്ല മൊരിഞ്ഞ ഉള്ളിവട',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'bonda',
    name: 'Nadan Bonda (Potato Fritter)',
    malayalamName: 'ബോണ്ട',
    price: 15,
    category: 'snacks',
    icon: '🥔',
    description: 'Spiced mashed potato filling inside a crunchy besan batter crust',
    malayalamDescription: 'ഉരുളക്കിഴങ്ങ് മസാല നിറച്ച ചൂട് ബോണ്ട',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'samosa',
    name: 'Kerala Samosa',
    malayalamName: 'സമൂസ',
    price: 15,
    category: 'snacks',
    icon: '🥟',
    description: 'Flaky triangular pastry stuffed with spicy potato & green peas masala',
    malayalamDescription: 'മൊരിഞ്ഞ നാടൻ സമൂസ',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'mutta_bajji',
    name: 'Mutta Bajji (Egg Bajji)',
    malayalamName: 'മുട്ട ബജ്ജി',
    price: 20,
    category: 'snacks',
    icon: '🥚',
    description: 'Boiled egg halves dipped in spiced chickpea batter and deep-fried',
    malayalamDescription: 'മസാലക്കൂട്ടിൽ മുക്കിപ്പൊരിച്ച മുട്ട ബജ്ജി',
    isHot: true,
  },
  {
    id: 'chicken_roll',
    name: 'Chicken Roll',
    malayalamName: 'ചിക്കൻ റോൾ',
    price: 40,
    category: 'snacks',
    icon: '🌯',
    description: 'Spicy shredded chicken stuffing wrapped in a crispy breaded crust',
    malayalamDescription: 'ചിക്കൻ മസാല നിറച്ച നല്ല മൊരിഞ്ഞ റോൾ',
    isHot: true,
  },

  // 🥤 തണുത്തത്
  {
    id: 'naranga_vellam',
    name: 'Naranga Vellam (Fresh Lime)',
    malayalamName: 'നാരങ്ങാവെള്ളം',
    price: 15,
    category: 'drinks',
    icon: '🍋',
    description: 'Freshly squeezed lime with rock salt, sugar and chilled village well water',
    malayalamDescription: 'ദാഹം മാറ്റാൻ നാടൻ നാരങ്ങാവെള്ളം',
    isVeg: true,
  },
  {
    id: 'kulukki_sarbat',
    name: 'Kulukki Sarbath',
    malayalamName: 'സർബത്ത്',
    price: 25,
    category: 'drinks',
    icon: '🍹',
    description: 'Shaken lemonade with sweet basil seeds (കഞ്ചാവ് വിത്ത്/സബ്ജ), green chillies & nannari syrup',
    malayalamDescription: 'കണ്ണൻ നാരങ്ങയും സബ്ജ വിത്തും നറുനീണ്ടിയും കുലുക്കിയെടുത്ത സർബത്ത്',
    isVeg: true,
  },
  {
    id: 'milk_shake',
    name: 'Cold Milk Shake',
    malayalamName: 'മിൽക്ക് ഷേക്ക്',
    price: 50,
    category: 'drinks',
    icon: '🥤',
    description: 'Thick chilled banana and chocolate milk shake with cashews',
    malayalamDescription: 'കട്ടപ്പാലും കശുവണ്ടിയും ചേർത്ത തണുത്ത മിൽക്ക് ഷേക്ക്',
    isVeg: true,
  },
  {
    id: 'soda',
    name: 'Chilled Goli Soda',
    malayalamName: 'സോഡ',
    price: 20,
    category: 'drinks',
    icon: '🍾',
    description: 'Fizzy carbonated marble soda that pops with refreshing fizz',
    malayalamDescription: 'കുപ്പി തുറക്കുമ്പോൾ പതയുന്ന നാടൻ സോഡ',
    isVeg: true,
  },
  {
    id: 'falooda',
    name: 'Malabar Royal Falooda',
    malayalamName: 'ഫാൽസൂദ',
    price: 60,
    category: 'drinks',
    icon: '🍨',
    description: 'Layered falooda with rose syrup, vermicelli, chia seeds, fruits & vanilla ice cream scoop',
    malayalamDescription: 'റോസ് സിറപ്പും ഐസ്ക്രീമും പഴങ്ങളും ചേർത്ത റോയൽ ഫലൂദ',
    isVeg: true,
  },

  // ⭐ THATTUKADA COMBO
  {
    id: 'combo_chaya_pazham',
    name: 'Chaya + Pazham Pori',
    malayalamName: 'ചായ + പഴംപൊരി',
    price: 25,
    category: 'combos',
    icon: '☕🍌',
    description: 'The golden Kerala sunset companion: Hot foamy milk tea paired with piping hot sweet banana fry.',
    malayalamDescription: 'വൈകുന്നേരങ്ങളിലെ ബെസ്റ്റ് കോമ്പോ — ചൂട് ചായയും പഴംപൊരിയും!',
    isHot: true,
    isVeg: true,
  },
  {
    id: 'combo_chaya_omelette_bread',
    name: 'Chaya + Omelette + Bread',
    malayalamName: 'ചായ + ഓംലറ്റ് + ബ്രെഡ്',
    price: 45,
    category: 'combos',
    icon: '☕🍳🥪',
    description: 'Power breakfast combo: Fresh bakery bread, spicy two-egg omelette and piping hot chai.',
    malayalamDescription: 'രാവിലത്തെ ബെസ്റ്റ് കോമ്പോ — ബ്രെഡ് ഓംലറ്റും കട്ടൻ ചായയും!',
    isHot: true,
  },
  {
    id: 'combo_porotta_chicken_chaya',
    name: 'Porotta + Chicken Fry + Chaya',
    malayalamName: 'പൊറോട്ട + ചിക്കൻ ഫ്രൈ + ചായ',
    price: 130,
    category: 'combos',
    icon: '🫓🍗☕',
    description: 'Ultimate Thattukada feast: 2 flaky porottas, crispy fried chicken with shallots & steaming hot tea.',
    malayalamDescription: 'തട്ടുകടയിലെ ഹിറ്റ് കോമ്പോ — ലെയർ പൊറോട്ട, മൊരിഞ്ഞ ചിക്കൻ ഫ്രൈ, ഒപ്പം ചൂട് ചായയും!',
    isHot: true,
    isSpicy: true,
  },
  {
    id: 'combo_kizhakkumpuram_special',
    name: 'Kizhakkumpuram Special (Porotta + Beef Fry + Chaya)',
    malayalamName: '🔥 KIZHAKKUMPURAM SPECIAL — പൊറോട്ട + ബീഫ് ഫ്രൈ + ചായ',
    price: 140,
    category: 'combos',
    icon: '🔥🥩🫓☕',
    description: 'The King of Kizhakkumpuram: 2 hot layered porottas, slow-roasted beef fry with coconut bites & a strong tea.',
    malayalamDescription: 'കിഴക്കുംപുറത്തിന്റെ സ്വന്തം സ്പെഷ്യൽ — ചൂട് പൊറോട്ടയും തേങ്ങാക്കൊത്തിട്ട ബീഫ് ഫ്രൈയും നല്ലൊരു ചായയും!',
    isHot: true,
    isSpicy: true,
  },

  // 🏆 UNLOCKED REPUTATION SPECIALS
  {
    id: 'secret_sulaimani',
    name: 'Nair Chettan’s Secret Spiced Sulaimani',
    malayalamName: 'നായരുടെ സ്പെഷ്യൽ സുലൈമാനി',
    price: 15,
    category: 'unlocked',
    icon: '✨🍋',
    description: 'Secret recipe with saffron, cinnamon, cloves, mint leaves & honey. Unlocked at Regular Customer level.',
    malayalamDescription: 'നായർ ചേട്ടന്റെ രഹസ്യ മസാലക്കൂട്ട് ചേർത്ത രാജകീയ സുലൈമാനി!',
    isHot: true,
    isVeg: true,
    requiredReputationLevel: 2,
  },
  {
    id: 'secret_double_beef',
    name: 'Double Roasted Spiced Beef Fry',
    malayalamName: 'ഡബിൾ ബീഫ് ഫ്രൈ സ്പെഷ്യൽ',
    price: 120,
    category: 'unlocked',
    icon: '✨🥩',
    description: 'Extra crispy beef cubes double-fried with fresh curry leaves & green chillies. Unlocked at Village Promani level.',
    malayalamDescription: 'നാട്ടിലെ പ്രമാണിമാർക്കായി പ്രത്യേകം വറുത്തെടുത്ത ഡബിൾ ബീഫ് ഫ്രൈ!',
    isHot: true,
    isSpicy: true,
    requiredReputationLevel: 3,
  },
  {
    id: 'secret_kizhi_porotta',
    name: 'Royal Kizhi Porotta Feast',
    malayalamName: 'രാജകീയ കിഴി പൊറോട്ട ഫീസ്റ്റ്',
    price: 150,
    category: 'unlocked',
    icon: '👑🫓🥩',
    description: 'Layered porottas with beef roast, chicken fry & boiled egg tied in fresh banana leaf and steamed on tawa. Unlocked at Thattukada VIP level.',
    malayalamDescription: 'വാഴയിലയിൽ പൊതിഞ്ഞ് തവയിൽ വച്ച് വാട്ടിയ രാജകീയ കിഴി പൊറോട്ട ഫീസ്റ്റ്!',
    isHot: true,
    isSpicy: true,
    requiredReputationLevel: 4,
  },
];
