import { WaypointDestination } from '../types';

export const MASTER_MAP_WAYPOINTS: WaypointDestination[] = [
  {
    id: 'wp_home',
    name: 'Player House (സ്വന്തം വീട്)',
    malayalamName: 'സ്വന്തം വീട് & മുറ്റം 🏠',
    icon: '🏠',
    coords: { x: -45, z: -10 },
    category: 'Village',
  },
  {
    id: 'wp_town_center',
    name: 'Kizhakkumpuram Town Center',
    malayalamName: 'ടൗൺ സെന്റർ & ക്ലോക്ക് ടവർ 🏙️',
    icon: '🏙️',
    coords: { x: 0, z: 0 },
    category: 'Transport',
  },
  {
    id: 'wp_chaya_kada',
    name: 'Nair’s Authentic Chaya Kada',
    malayalamName: 'നായരുടെ ചായക്കട ☕',
    icon: '☕',
    coords: { x: -65, z: -18 },
    category: 'Shop',
  },
  {
    id: 'wp_bus_station',
    name: 'KSRTC & Coach Bus Stand',
    malayalamName: 'കെ.എസ്.ആർ.ടി.സി ബസ് സ്റ്റാൻഡ് 🚌',
    icon: '🚌',
    coords: { x: 24, z: 14 },
    category: 'Transport',
  },
  {
    id: 'wp_petrol_pump',
    name: 'Indian Oil Petrol Pump',
    malayalamName: 'ഇന്ത്യൻ ഓയിൽ പെട്രോൾ പമ്പ് ⛽',
    icon: '⛽',
    coords: { x: 35, z: 15 },
    category: 'Fuel',
  },
  {
    id: 'wp_auto_garage',
    name: 'Village Auto & Bus Workshop',
    malayalamName: 'കിഴക്കുംപുറം വർക്ക്ഷോപ്പ് 🔧',
    icon: '🔧',
    coords: { x: -25, z: 25 },
    category: 'Fuel',
  },
  {
    id: 'wp_daily_bazaar',
    name: 'Daily Bazaar & Fish Market',
    malayalamName: 'ചന്തയും മീൻ മാർക്കറ്റും 🛍️',
    icon: '🛍️',
    coords: { x: 85, z: 10 },
    category: 'Shop',
  },
  {
    id: 'wp_sevens_ground',
    name: 'Kizhakkumpuram Sevens Stadium',
    malayalamName: 'സെവൻസ് ഫുട്ബോൾ സ്റ്റേഡിയം ⚽',
    icon: '⚽',
    coords: { x: 110, z: -80 },
    category: 'Sports',
  },
  {
    id: 'wp_school',
    name: 'St. Mary’s Govt High School',
    malayalamName: 'സെന്റ് മേരീസ് സ്കൂൾ 🏫',
    icon: '🏫',
    coords: { x: 100, z: -70 },
    category: 'Village',
  },
  {
    id: 'wp_hospital',
    name: 'Taluk Govt Hospital & 108 Ambulance',
    malayalamName: 'താലൂക്ക് ആശുപത്രി 🏥',
    icon: '🏥',
    coords: { x: 18, z: 65 },
    category: 'Village',
  },
  {
    id: 'wp_juma_masjid',
    name: 'Serene Juma Masjid (പള്ളി)',
    malayalamName: 'കിഴക്കുംപുറം ജുമാ മസ്ജിദ് 🕌',
    icon: '🕌',
    coords: { x: -72, z: -42 },
    category: 'Village',
  },
  {
    id: 'wp_paddy_tractor',
    name: 'Paddy Fields & Tractor Stand',
    malayalamName: 'പച്ചപ്പ് നിറഞ്ഞ നെൽപ്പാടം 🌾',
    icon: '🌾',
    coords: { x: -130, z: 90 },
    category: 'Nature',
  },
  {
    id: 'wp_lotus_pond',
    name: 'Lotus Pond (താമരക്കുളം)',
    malayalamName: 'താമരക്കുളവും പടവുകളും 🪷',
    icon: '🪷',
    coords: { x: -80, z: -75 },
    category: 'Nature',
  },
  {
    id: 'wp_river_bridge',
    name: 'Big River Highway Bridge',
    malayalamName: 'വലിയ പുഴ ഹൈവേ പാലം 🌉',
    icon: '🌉',
    coords: { x: 0, z: 145 },
    category: 'Transport',
  },
  {
    id: 'wp_backwater_jetty',
    name: 'Backwater Houseboat Jetty',
    malayalamName: 'കായലും കെട്ടുവള്ള ജെട്ടിയും 🛶',
    icon: '🛶',
    coords: { x: 120, z: 230 },
    category: 'Nature',
  },
  {
    id: 'wp_lighthouse_beach',
    name: 'South Coast Lighthouse Beach',
    malayalamName: 'ലൈറ്റ്ഹൗസ് ബീച്ചും കടലും 🏖️',
    icon: '🏖️',
    coords: { x: 0, z: 320 },
    category: 'Nature',
  },
  {
    id: 'wp_mountain_viewpoint',
    name: 'North Hills Viewpoint & Ghats',
    malayalamName: 'മലവാരവും വ്യൂ പോയിന്റും ⛰️',
    icon: '⛰️',
    coords: { x: 0, z: -280 },
    category: 'Nature',
  },
  {
    id: 'wp_teak_forest',
    name: 'Dense Teak Forest & Offroad Trails',
    malayalamName: 'തേക്ക് കാടും കാട്ടുപാതയും 🌲',
    icon: '🌲',
    coords: { x: -140, z: -250 },
    category: 'Nature',
  },
];
